
use sachin;
create table EMPLOYEE(DATE VARCHAR(30) ,
EMP_ID BIGINT,
NAME VARCHAR(20),
DESIGNATION VARCHAR(40));

INSERT INTO EMPLOYEE(DATE,EMP_ID,NAME,DESIGNATION)
VALUES ('1-NOV-18',1101,'ARUN','PROGRAMMER'),
('1-NOV-18',1102,'RAHUL','SOFT ENG'),
('3-NOV-18',1103,'SACHIN','SALES EXECUTIVE');

ALTER TABLE EMPLOYEE ADD PRIMARY KEY (EMP_ID);
ALTER TABLE EMPLOYEE ADD COLUMN(ADRESS VARCHAR(10));
SELECT*FROM EMPLOYEE;
drop table EMPLOYEE;
